# Generated by Django 3.0.5 on 2021-02-01 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_level', models.IntegerField(default=1)),
                ('hit_die', models.CharField(max_length=100)),
                ('primary_ability', models.CharField(max_length=10)),
                ('saving_throws', models.CharField(max_length=100)),
                ('armor_proficiency', models.CharField(max_length=100)),
                ('weapon_proficiency', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('ability_score_increase', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('alignment', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('speed', models.IntegerField(default=20)),
                ('languages', models.CharField(max_length=200)),
                ('darkvision', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Races',
            },
        ),
        migrations.CreateModel(
            name='SubRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subrace_ability_score_increase', models.CharField(max_length=100)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pjs.Race')),
            ],
            options={
                'verbose_name_plural': 'Subraces',
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pjs.Class')),
            ],
            options={
                'verbose_name_plural': 'Features',
            },
        ),
    ]
