# Generated by Django 3.0.5 on 2021-02-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='pito',
            field=models.CharField(default='pene', max_length=100),
            preserve_default=False,
        ),
    ]
