# Generated by Django 3.0.5 on 2021-02-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjs', '0002_race_pito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='pito',
        ),
        migrations.AddField(
            model_name='race',
            name='desc',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
