# Generated by Django 3.0.5 on 2021-02-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjs', '0004_auto_20210201_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='descr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='descr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subrace',
            name='descr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
